<h1>aaa.html</h1>

<form action="<?= $block->getFormUrl(); ?>" method="post" class="form" id="myform1" data-mage-init='{"validation":{}}'>
    <fieldset>
        <div>
            <label for="name">name</label>
            <input type="text" name="name" >
        </div>
        <div>
            <label for="content">content</label>
            <input type="text" name="post_content" >
        </div>
    </fieldset>
    <div><input type="submit" value="submit"></div>
</form>

<hr>
<div>
    <?php
        $row = $block->getOne();
    ?>
    <span><?php echo $row->getPostId() ?></span>
    <span><?php echo $row->getName() ?></span>
    <span><?php echo $row->getPostContent() ?></span>
</div>
<hr>
<table>
    <tr>
        <th class="post-id">ID</th>
        <th class="post-name">Name</th>
        <th>Content</th>
    </tr>
    <?php foreach($block->getPostCollection() as $key => $post){ ?>
        <tr>
            <td><?= $post->getPostId(); ?></td>
            <td><?= $post->getName(); ?></td>
            <td><?= $post->getPostContent(); ?></td>
        </tr>
    <?php } ?>
</table>