<?php
    /**
     * @var \Huang\HelloWorld\Block\Index $block
     */
    echo $block->sayHello();
?>
<hr>
<h1>index. html</h1>

<hr>
<table>
    <tr>
        <th class="post-id">ID</th>
        <th class="post-name">Name</th>
        <th>Content</th>
    </tr>
    <?php foreach($block->getPostCollection() as $key=>$post){?>
        <tr>
            <td><?=$post->getPostId()?></td>
            <td><?=$post->getName()?></td>
            <td><?=$post->getPostContent()?></td>
        </tr>
    <?php }?>
</table>